# Generated by Django 5.0.1 on 2024-07-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculte',
            name='universite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbord.universite'),
        ),
    ]
