# Generated by Django 5.0.1 on 2024-07-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0002_alter_faculte_universite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbord.entreprise'),
        ),
    ]
