# Generated by Django 5.0.1 on 2024-07-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_etudiant_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbord.faculte'),
        ),
    ]
