# Generated by Django 5.0.1 on 2024-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0005_alter_stage_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
