# Generated by Django 5.0.1 on 2024-07-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0006_alter_stage_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='encadeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
