# Generated by Django 5.0.1 on 2024-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0007_stage_encadeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
