# Generated by Django 5.0.1 on 2024-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0008_etudiant_email_etudiant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
