# Generated by Django 4.0.4 on 2024-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0010_remove_etudiant_universite_remove_faculte_universite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculte',
            name='email',
            field=models.EmailField(default='exemple@gmail.com', max_length=254),
        ),
    ]
