# Generated by Django 4.0.4 on 2024-07-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0011_alter_faculte_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universite',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
