# Generated by Django 4.0.4 on 2024-07-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0013_alter_entreprise_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='nom',
        ),
    ]
