# Generated by Django 4.0.4 on 2024-07-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0014_remove_entreprise_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(default='mike', max_length=200),
            preserve_default=False,
        ),
    ]
