# Generated by Django 4.0.4 on 2024-07-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0015_entreprise_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isUnversite',
            new_name='isFaculte',
        ),
    ]
