# Generated by Django 4.0.4 on 2024-07-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0016_rename_isunversite_user_isfaculte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='faculte',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
