# Generated by Django 4.0.4 on 2024-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0018_stage_isstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='date_inscription',
            field=models.DateField(null=True),
        ),
    ]
