# Generated by Django 4.0.4 on 2024-07-18 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0020_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotation',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbord.entreprise'),
        ),
    ]
