# Generated by Django 4.0.4 on 2024-07-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0021_cotation_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='filiere_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashbord.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
