# Generated by Django 4.0.4 on 2024-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0022_etudiant_filiere_relation_alter_etudiant_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotation',
            name='isCotation',
            field=models.BooleanField(default=False),
        ),
    ]
