# Generated by Django 4.0.4 on 2024-08-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0023_cotation_iscotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='email',
        ),
    ]
